# docker-compose.yml
version: "3.5"
services:
    server:
        build: ./rexurl/
        restart: always
        ports:
            - 8080:8080
        environment:
          DB_HOST: db
          DB_USERNAME: root
          DB_PASSWORD: pwd
        networks:
            - db-net
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        volumes:
        - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: pwd
            MYSQL_DATABASE: db_rexurl
        networks:
            - db-net
        ports:
            - 3306:3306

networks:
    db-net: